{% set name = "geodatatool" %}
{% set version = "0.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2900ecd3c051b0c9dc9dfb1e228b6e7ac11f07f90936fc197bf1491ca4c1fd60

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - earthengine-api
    - folium
    - ipyleaflet
    - pillow
    - pyshp
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - geodatatool

about:
  home: "https://github.com/clancygeodata/geodatatool"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python package for geographic data tools"
  doc_url: https://clancygeodata.github.io/geodatatool
  dev_url: https://github.com/clancygeodata/geodatatool

extra:
  recipe-maintainers:
    - clancygeodata
